# Generated by Django 6.0.3 on 2026-05-13 16:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.IntegerField(choices=[(0, 'INC'), (1, 'REQ'), (2, 'PRB'), (3, 'CHG')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('fk_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicedesk.department')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=250)),
                ('shortname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_staff', models.BooleanField(default=False)),
                ('fk_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicedesk.job')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stage', models.IntegerField(choices=[(0, 'Новое'), (1, 'Классифицируется'), (2, 'Назначен'), (3, 'Решён'), (4, 'Закрыт')], default=0)),
                ('priority', models.IntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], default=0)),
                ('description', models.CharField(max_length=1000)),
                ('datetime_registered', models.DateTimeField()),
                ('datetime_classified', models.DateTimeField(blank=True, null=True)),
                ('datetime_assigned', models.DateTimeField(blank=True, null=True)),
                ('datetime_diagnosed', models.DateTimeField(blank=True, null=True)),
                ('datetime_solved', models.DateTimeField(blank=True, null=True)),
                ('datetime_closed', models.DateTimeField(blank=True, null=True)),
                ('datetime_deadlinne', models.DateTimeField(blank=True, null=True)),
                ('is_stopped', models.BooleanField(default=False)),
                ('fk_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicedesk.service')),
                ('fk_initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to='servicedesk.user')),
                ('fk_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='servicedesk.user')),
            ],
        ),
    ]
