# Generated by Django 6.0.3 on 2026-06-06 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_priority',
            field=models.IntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='default_time_to_solve',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Новое'), (1, 'Классифицирован'), (2, 'Назначен'), (3, 'Решён'), (4, 'Закрыт')], default=0),
        ),
    ]
