# Generated by Django 6.0.3 on 2026-05-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0002_alter_ticket_datetime_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fk_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='servicedesk.user'),
        ),
    ]
