# Generated by Django 6.0.3 on 2026-05-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0003_alter_ticket_fk_responsible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fulname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='shortname',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
