# Generated by Django 6.0.3 on 2026-05-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0004_rename_fulname_user_fullname_remove_job_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Новое'), (1, 'Классифицируется'), (2, 'Назначен'), (3, 'Решён'), (4, 'Закрыт')], default=0),
        ),
    ]
